on:
  workflow_dispatch:
  push:

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::410793108087:role/github-actions-oidc
      - run: |
         Install-Module -Name AWS.Tools.EC2 -Force
         Get-EC2Vpc
        shell: pwsh
